default['wordpress']['base_dir'] = '/var/www/html'
default['wordpress']['git_repo'] = 'github.com/patilmahadev/wordpress.git'
default['wordpress']['dbname'] = 'wordpress'
default['wordpress']['dbuser'] = 'root'
default['wordpress']['dbpassword'] = 'root1234'
default['wordpress']['dbhost'] = 'localhost'
default['wordpress']['dbport'] = '3306'
